name: '*nixing around'
description: >
    Cut-and-paste walkthroughs of complicated projects
about: >
    This blog is the sort of thing I wish I'd been able to find when I first started messing with programs and linux - ok, it's what I still hope to find when I research things.  It's intended for people who are way out of their depth, but still want to forge ahead with their cool project.  This is a place where I'm recording how I did things, step by step, with no assumptions of prior knowledge except how to paste into a linux command line.  So that mostly just describes myself.  I'll probably forget how I did this stuff, and I want to remember how.  Plus, it helps me stay on track when I'm writing it down as I go.  This is my research journal.


url: "https://umhau.github.io"
#baseurl: "/white-paper" 
markdown: kramdown
highlighter: rouge
future: true

gems: [jekyll-paginate,  jekyll-gist]

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           um.hau
  avatar:         ""
  email:          "um.hau@outlook.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github: umhau
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
